name: Flutter CI

on:
  push:
    branches: [set-pipeline]
jobs:
  version:
    name: Create version number
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Fetch all history for all tags and branches
        run: |
          git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git fetch --prune --depth=10000
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Create version.txt with nuGetVersion
        run: echo ${{ steps.gitversion.outputs.nuGetVersion  }} > version.txt
      - name: Upload version.txt
        uses: actions/upload-artifact@v2
        with:
          name: gitversion
          path: version.txt
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get version.txt
        run: |
          curl -o version.txt -L "your-artifact-url-here" # Replace with the URL of your artifact
          cat version.txt
          echo "Version file retrieved."

      - name: Set Version
        id: set_version
        run: |
          VERSION=$(cat version.txt)
          echo "::set-output name=version::$VERSION"
        shell: bash

      - name: Update Version in pubspec.yaml
        run: |
          sed -i "s/99.99.99+99/${{ steps.set_version.outputs.version }}+${{ github.run_number }}/g" pubspec.yaml
        shell: bash

      - name: Update KeyStore Password
        run: |
          echo "KEYSTORE_PASS=${{ secrets.KEYSTORE_PASS }}" >> $GITHUB_ENV
          sed -i 's/#{KEYSTORE_PASS}#/$KEYSTORE_PASS/g' android/key.properties
        shell: bash

      - name: Update KeyStore Key Password
        run: |
          echo "KEYSTORE_KEY_PASS=${{ secrets.KEYSTORE_KEY_PASS }}" >> $GITHUB_ENV
          sed -i 's/#{KEYSTORE_KEY_PASS}#/$KEYSTORE_KEY_PASS/g' android/key.properties
        shell: bash

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 12.x # Change to your desired Java version

      - name: Set up Flutter
        uses: subosito/flutter-action@v4
        with:
          flutter-version: beta

      - name: Flutter Clean
        run: flutter clean

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Build App Bundle
        run: flutter build appbundle --release

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/apk/release/*.apk
            build/app/outputs/bundle/release/app-release.aab
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.set_version.outputs.version }}
          title: Release ${{ steps.set_version.outputs.version }}

      - name: Upload App Bundle
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab
  # release:
  #   name: Release app to internal track
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Get appbundle from artifacts
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: appbundle
  #     - name: Release app to internal track
  #       uses: r0adkll/upload-google-play@v1
  #       with:
  #         serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
  #         packageName: com.app.package_name
  #         releaseFiles: app-release.aab
  #         track: alpha
  #         status: completed