name: task-minder

on:
  push:
    branches:
      - set-pipeline

jobs:
  version:
    name: Get Version
    runs-on: ubuntu-latest
    steps:
      - name: Get version.txt
        uses: actions/download-artifact@v2
        with:
          name: gitversion
      - name: Create new file without newline char from version.txt
        run: tr -d '\n' < version.txt > version1.txt
      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: version1.txt

  build:
    name: Build APK and Create release
    needs: [version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update version in YAML
        run: sed -i 's/99.99.99+99/${{ steps.version.outputs.content }}+${{ github.run_number }}/g' pubspec.yaml
      # ... (rest of your steps)

  # Add an additional job with no dependencies
  no-dependency-job:
    name: No Dependency Job
    runs-on: ubuntu-latest
    steps:
      - name: This is a job with no dependencies
        run: echo "This job has no dependencies."

